### ISSUE TITLE
[BUG] Auto-play fails in playlist on short playlist items sometimes

### ISSUE THREAD

**Issue by elynema** [samvera-labs/ramp#375]
# Description

I am seeing significant auto-play weirdness with short clips (like 10 seconds). The auto-play is skipping right over these playlist items. They seem to play fine when you actually click on them.

Here is an example of the errors in the console when this happens:

```
video.es.js:229 VIDEOJS: ERROR: TypeError: Cannot read properties of null (reading 'duration')
    at DurationDisplay.updateContent (video.es.js:12348:1)
    at DurationDisplay.updateContent (video.es.js:12301:1)
    at data.dispatcher (video.es.js:2312:1)
    at trigger (video.es.js:2448:1)
    at Player.trigger$1 [as trigger] (video.es.js:3390:1)
    at Player.<computed> [as handleTechLoadedmetadata_] (video.es.js:27535:1)
    at Player.<anonymous> (video.es.js:23230:1)
    at data.dispatcher (video.es.js:2312:1)
(anonymous) @ video.es.js:229
log.error @ video.es.js:417
data.dispatcher @ video.es.js:2314
trigger @ video.es.js:2448
trigger$1 @ video.es.js:3390
Player.<computed> @ video.es.js:27535
(anonymous) @ video.es.js:23230
data.dispatcher @ video.es.js:2312
Show 8 more frames
Show less
ramp.umd.js:4519 loadedmetadata
video.es.js:229 VIDEOJS: TypeError: Cannot set properties of null (setting 'currentTime')
    at Html5.setCurrentTime (video.es.js:20522:1)
    at set (video.es.js:10101:1)
    at Player.<anonymous> (video.es.js:24373:1)
    at Player.ready (video.es.js:4476:1)
    at Player.techCall_ (video.es.js:24371:1)
    at Player.currentTime (video.es.js:24644:1)
    at Player.<anonymous> (ramp.umd.js:4565:1)
    at data.dispatcher (video.es.js:2312:1)
    at trigger (video.es.js:2448:1)
    at Player.trigger$1 [as trigger] (video.es.js:3390:1)
    at Player.<computed> [as handleTechLoadedmetadata_] (video.es.js:27535:1)
    at Player.<anonymous> (video.es.js:23230:1)
    at data.dispatcher (video.es.js:2312:1) Video is not ready. (Video.js)
video.es.js:229 VIDEOJS: ERROR: TypeError: Cannot read properties of null (reading 'videoWidth')
    at Html5.<computed> [as videoWidth] (video.es.js:21840:1)
    at Player.videoWidth (video.es.js:26759:1)
    at Player.updateStyleEl_ (video.es.js:23117:1)
    at Player._this.boundUpdateStyleEl_ (video.es.js:22367:1)
    at data.dispatcher (video.es.js:2312:1)
(anonymous) @ video.es.js:229
log.error @ video.es.js:417
data.dispatcher @ video.es.js:2314
Show 3 more frames
Show less
video.es.js:21990 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'play')
    at Html5.<computed> [as play] (video.es.js:21990:1)
    at mediate (video.es.js:10137:1)
    at Player.techGet_ (video.es.js:24409:1)
    at Player.play_ (video.es.js:24507:1)
    at video.es.js:24456:1
    at new Promise (<anonymous>)
    at Player.play (video.es.js:24455:1)
    at Player.<anonymous> (ramp.umd.js:4567:1)
    at data.dispatcher (video.es.js:2312:1)
    at trigger (video.es.js:2448:1)
    at Player.trigger$1 [as trigger] (video.es.js:3390:1)
    at Player.<computed> [as handleTechLoadedmetadata_] (video.es.js:27535:1)
    at Player.<anonymous> (video.es.js:23230:1)
    at data.dispatcher (video.es.js:2312:1)
```

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemttQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a2c9bce0e1810584750059934a737b63661260f/Screen%20Recording%202024-02-02%20at%203.19.23%20PM.mov)

This seems to be happening across browsers. You should be able to replicate with this playlist: https://avalon-dev.dlib.indiana.edu/playlists/56. Try allowing auto-play to advance to playlist item #6 (Kalila wa Dimna) or #25 (Kittens). The item is skipped over and a bunch of errors show up in the console. I've only seen this happen with short items at this point, but not all short items. If you allow auto-play to advance to playlist item #13, it plays fine, even with a playlist item description.

I have had this happen in both playlists that I tested with with short items of about 10 seconds or less.

I happened to discover this when testing playlist item descriptions, but I think it is a generic bug unrelated to playlist item descriptions, because I have seen it occur when there is no description and when the description has been deleted.

**Comment by joncameron** [comment]
Could be fixed by the most recent Ramp build; needs retesting.

**Comment by elynema** [comment]
Re-tested; this is still happening for me after computer reboot and hard refresh. The previous / next canvas do a better job of finding these short items than auto-play does.

**Comment by elynema** [comment]
I tried to see if I could replicate this on a media item, but so far, haven't been able to. I have only tried this one so far: https://avalon-dev.dlib.indiana.edu/media_objects/mw22v546v

**Comment by joncameron** [comment]
Test with https://avalon-dev.dlib.indiana.edu/playlists/56 at ramp.dlib.indiana.edu and this seems resolved; will retest in Avalon after a new Ramp build.
